# Generated by Django 5.1.4 on 2024-12-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the staff member', max_length=100)),
                ('role', models.CharField(help_text='Role or position of the staff member', max_length=100)),
                ('bio', models.TextField(help_text='A short bio of the staff member')),
                ('photo', models.ImageField(help_text='Upload a photo of the staff member', upload_to='staff_photos/')),
                ('twitter', models.URLField(blank=True, help_text='Twitter profile link', null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook profile link', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile link', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile link', null=True)),
            ],
        ),
    ]
